### ISSUE TITLE
Mysql database no tables

### ISSUE THREAD

**Issue by clsx524** [VertaAI/modeldb#2012]
Hi, I am trying to use mysql as the database. I pulled the code and built it locally and have modeldb-backend image available. When I started the server, it complained about “missing table [artifact]” and the database is empty. Do you know why the tables are not created automatically?

My config file
```
#This config is used by docker compose.
#ModelDB Properties
grpcServer:
  port: 8085

springServer:
  port: 8086
  shutdownTimeout: 30 #time in second

artifactStoreConfig:
  artifactStoreType: NFS #S3, GCP, NFS
  host: modeldb-backend
  protocol: http
  NFS:
    nfsUrlProtocol: http
    nfsRootPath: /artifact-store/
    artifactEndpoint:
      getArtifact: "api/v1/artifact/getArtifact"
      storeArtifact: "api/v1/artifact/storeArtifact"

database:
  DBType: relational
  timeout: 4
  liquibaseLockThreshold: 60 #time in second
  RdbConfiguration:
    RdbDatabaseName: modeldb
    RdbDriver: "com.mysql.cj.jdbc.Driver"
    RdbDialect: "org.hibernate.dialect.MySQL8Dialect"
    RdbUrl: "jdbc:mysql://mysqldb:3306"
    RdbUsername: user
    RdbPassword: verybigsecret

# Test Database settings (type mongodb, couchbasedb etc..)
test:
  database:
    DBType: relational
    timeout: 4
    liquibaseLockThreshold: 60 #time in second
    RdbConfiguration:
      RdbDatabaseName: modeldb
      RdbDriver: "com.mysql.cj.jdbc.Driver"
      RdbDialect: "org.hibernate.dialect.MySQL8Dialect"
      RdbUrl: "jdbc:mysql://mysqldb:3306"
      RdbUsername: user
      RdbPassword: verybigsecret

cron_job:
  update_parent_timestamp:
    frequency: 10 #frequency to update parent timestamp in second, default 60
    record_update_limit: 100
  delete_entities:
    frequency: 60 #frequency to update parent timestamp in second, default 60
    record_update_limit: 100
```
