### ISSUE TITLE
Backend docker not working 

### ISSUE THREAD

**Issue by shukla-deepesh** [VertaAI/modeldb#287]
As per the instruction installed docker for Mongodb m backend and Frontend.  But the backend docker doesnot run .   
Also when I do docker exec -it backend ps -a   no service is running .

I tried executing start_server,sh 0.10.0  command as well it build successfully but still does not run any service.

**Comment by FernandoBontorin** [comment]
Same here, I configure the docker-compose.yml to run with official latest images:
```yaml
version: '3'

services:
  mongo:
    image: mongo:3.4
    networks:
      default:
        aliases:
          - mongo
    ports:
      - "27017:27017"
  backend:
    image: mitdbg/modeldb-backend:latest
    networks:
      default:
        aliases:
          - backend
    ports:
      - "6543:6543"
    command: ["mongo"]
  frontend:
    image: mitdbg/modeldb-frontend:latest
    networks:
      default:
        aliases:
          - frontend
    ports:
      - "3000:3000"
    command: ["backend"]
```



and I get the follow log when docker-compose up
```
backend_1   | MongoDB is up - executing command
backend_1   | here
backend_1   | touch: cannot touch '/db/some': No such file or directory
```
after the last line the container of backend crash
